name: Build and Push Container Image

on:
  push:
    tags:
      - "*" # Trigger on any tag

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract tag version
        id: tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Set image name
        id: image
        run: |
          echo "NAME=couchdb-ols" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.image.outputs.NAME }}:${{ steps.tag.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.image.outputs.NAME }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ steps.image.outputs.NAME }}:${{ steps.tag.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/${{ steps.image.outputs.NAME }}:latest
